# Each workflow must have a name
# Here the workflow will be named as Sample Workflow
name: Sample workflow

# Each workflow is triggered on some events
# will be triggered on push
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  springboot-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distributions: ' temurin'
        cache: maven
    - name: Test with maven
      run: mvn -B test

  snyk-scanning:
    needs: springboot-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    